spring.application.name=minhaacademiaonline-api
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=b32cd8a36f00fffac87eb9bf12f52cb1ff784e0676e0ff1d93df6051b6a91589
spring.datasource.password=sk_Z55ekNzo8C0_od7Kiw5pB

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret="7vnYeTQQscsm+GTDRaXukkLQF3GxHcNNk9ehs9VEaaEHviWAy/htyOGcmiFlGiceR9aiyr8rKFmwCQ5Cg/g39w=="

# 1 Semana = 7 dias x 24 horas x 60 minutos x 60 segundos x 1000 ms
jwt.expiration=604800000 

asaas_api_key="asd"
